import { Inter,Open_Sans, Roboto_Mono,Playfair_Display, Poppins } from "next/font/google";
import "@radix-ui/themes/styles.css";
import { Theme } from "@radix-ui/themes";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const playfair_Display = Playfair_Display({subsets : ["latin"],variable: "--font-playfair",})
const poppins = Poppins({subsets : ["latin"],variable: "--font-Poppins",weight : ["100","300","500","700"]})
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const openSans = Open_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-opensans",
});
const robotoMono = Roboto_Mono({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto-mono",
});
export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${openSans.variable} ${robotoMono.variable} ${playfair_Display.variable} ${poppins.variable} font-sans`}
    >
      <body className={inter.className}>
        <Theme>{children}</Theme>
      </body>
    </html>
  );
}
